import type { Metadata } from "next";
import "../globals.css";
import UserLayout from "../components/UserLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <body className="antialiased">
        <UserLayout>{children}</UserLayout>
      </body>

  );
}
