import type { Metadata } from "next";
import "../globals.css";
import UserLayout from "../components/UserLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="antialiased">
      <UserLayout>{children}</UserLayout>
    </div>
  );
}

